### ISSUE TITLE
Why does this work?

### ISSUE THREAD

**Issue by Mike4U** [collin80/due_can#11]
Hi collin80,
Great work!  I'm using SavvyCan(OSX) with GVRET  on a Togglebit due Shield with my own SWCan addition to look at the Chevy Spark EV.  I'm capturing frames!  Looking forward to more cool stuff in SavvyCan.

What I don't understand is how the can1 pin assignments work in variant.h:
CANRX = 68 and CANTX = 69 for can0 seem ok and match the due pins
CAN1RX = 88 and CAN1TX = 89 seem like they should be 66 and 53?

Thanks for your help.  Is there a better place to post a question like this?

**Comment by collin80** [comment]
I believe the pin numbers refer to a different scheme. They aren't digital pin numbers but I think the actual hardware pins. At any rate, it does work. ;)
