### ISSUE TITLE
Help with CAN

### ISSUE THREAD

**Issue by ykupas** [collin80/due_can#20]
Good afternoon.
I'm doing a project with Arduino DUE to their due_can library. But I have a problem. The function Can1.available( ) does return a value of 0. I'm sure all the hardware and software are correct. If possible, I would like your help. Thank you very much.

**Comment by mwl** [comment]
Hello @ykupas.

I appreciate that this issue is almost a year old, but have you had any luck since you created the issue?

Disclaimer: I'm just a user of due_can, who's trying to help.

**Comment by ykupas** [comment]
Yes, it work perfectly on Arduino Due with Rs = 10k (CAN Tranciever pin -
10k - GND)
