### ISSUE TITLE
can_common.h: No such file - Where can I find it ?

### ISSUE THREAD

**Issue by Corbomit** [collin80/due_can#30]
Hello,
I got the error
_In file included from ...Arduino/libraries/due_can/due_can.h:23:24: fatal error: can_common.h: No such file or directory #include <can_common.h>_
A Google nor Github Search found anything, where can I find that file ?

**Comment by collin80** [comment]
Sorry, I should have updated the readme file for GVRET. There is a new library now that causes due_can and mcp2515 to be able to use a common API and be referred to by a common base class name.

https://github.com/collin80/can_common

**Comment by Corbomit** [comment]
Wow, that was fast ! Thank you. :-)
