### ISSUE TITLE
DUE_CAN using interrupts

### ISSUE THREAD

**Issue by skrenda** [collin80/due_can#43]
Hello, 

I'm looking for example of code using interrupt when CAN packet is recieved.
I can not use main loop to check if data arrived.
Is possible to use your library with interrupt handling? 

Thank you

Regards Skrenda

**Comment by collin80** [comment]
Yes, the library itself is always interrupt driven in the background. You can poll in your main loop but what that is really doing is checking a queue maintained by the interrupt handler. You can also directly have the interrupt send you the frame when it comes in. This is done via callbacks in the library. So, look at the various examples that use callbacks (they have CB in them). These should show you how to do it.

**Comment by skrenda** [comment]
Hello Colin,
 
thank you very much, I some how missed these examples. Sorry.
 
Regards Skrenda
______________________________________________________________
> Od: "Collin Kidder" <notifications@github.com>
> Komu: "collin80/due_can" <due_can@noreply.github.com>
> Datum: 04.01.2020 23:35
> Předmět: Re: [collin80/due_can] DUE_CAN using interrupts (#43)
>
> CC: <author@noreply.github.com>
Yes, the library itself is always interrupt driven in the background. You can poll in your main loop but what that is really doing is checking a queue maintained by the interrupt handler. You can also directly have the interrupt send you the frame when it comes in. This is done via callbacks in the library. So, look at the various examples that use callbacks (they have CB in them). These should show you how to do it.
