### ISSUE TITLE
Confirm receiving 

### ISSUE THREAD

**Issue by bbd556** [collin80/due_can#45]
How can i undrestand that my data frame has been received by receiver device?is there any confirmation code ?

**Comment by bbd556** [comment]
Plz help me!!!

**Comment by collin80** [comment]
Well, as the library sits, no. But, technically the hardware does know if the frame was successfully received by another node or not. I'd have to look into it some more but it should be possible to add such functionality to the library. There should be an interrupt that can fire when the message is successfully sent.

**Comment by bbd556** [comment]
> Well, as the library sits, no. But, technically the hardware does know if the frame was successfully received by another node or not. I'd have to look into it some more but it should be possible to add such functionality to the library. There should be an interrupt that can fire when the message is successfully sent.

**Comment by bbd556** [comment]
Thanks  very much mr collin for your useful library and your responsibility about users.
